on:
  push:
    branches:
      - branch











jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'printing text files'
        run: ls

      - uses: actions/checkout@v3

      - name: 'printing text '
        run: ls  